site_name: Azure Container Services - Workshop
site_description: Azure Container Services - Workshop
site_author: Roberto Borges
nav:
  - Homepage: index.markdown
  - Workshop Introduction:
    - aca/00-workshop-intro/index.md
    - ACA Core Components Overview: aca/00-workshop-intro/1-aca-core-components.md
    - Scenario and Solution Architecture: aca/00-workshop-intro/2-scenario-architecture.md
    - Dapr Integration in ACA: aca/00-workshop-intro/3-dapr-integration.md
    - Prerequisites: aca/00-workshop-intro/4-prerequisites.md
  - Module 1 - Deploy Backend API to ACA: aca/01-deploy-api-to-aca/index.md
  - Module 2 - Communication between Microservices in ACA: aca/02-aca-comm/index.md
  - Module 3 - Deploy Backend API to ACI: aca/03-deploy-api-to-aci/index.md
  - Module 4 - Deploy Fontend APP to App Service: aca/04-deploy-api-to-app/index.md
  - Module 5 - Deploy Backend API to AKS: aca/05-deploy-api-to-aks/index.md
  - Module 6 - Deployment Via Bicep and DevOps:
    - aca/06-aca-iac-bicep/index.md
    - Deploy Infrastructure using Bicep: aca/06-aca-iac-bicep/iac-bicep.md
    - Deploy Infrastructure using Bicep via GitHub Actions: aca/06-aca-iac-bicep/ci-cd-git-action.md
    - Deploy infrastructure using Azure Devops Pipeline: aca/06-aca-iac-bicep/ci-cd-azdo.md
  - Contributing:
    - Contribution Guide: aca/12-contributing/1-contribution-guide.md
    - Submit An Issue or Suggestion: aca/12-contributing/2-Submit-issue-suggestion.md
    - Minor Update or fix, New Challenge: aca/12-contributing/3-minor-update-fix.md
  - Appendix:
    - Debug and Launch Dapr Applications in VSCode: aca/13-appendix/01-run-debug-dapr-app-vscode.md
    - Testing Changes Locally or with GitHub Codespaces: aca/13-appendix/02-github-local-codespaces.md
  
theme:
  name: material
  custom_dir: docs/overrides
  font:
    text: Ubuntu
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - header.autohide
    - navigation.instant
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
  icon:
    repo: fontawesome/brands/github
  logo: assets/images/00-workshop-intro/02884-icon-service-Worker-Container-App.svg
  favicon: assets/images/00-workshop-intro/02884-icon-service-Worker-Container-App.svg

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.keys
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.snippets:
      base_path: '.'
      check_paths: true
      url_download: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - meta
  - toc:
      permalink: true
      toc_depth: 4
  - attr_list
  - md_in_html

copyright: Copyright &copy; 2023 Microsoft

plugins:
  - git-revision-date
  - search
  - macros
  - glightbox

extra:
  dapr:
    version: 1.9.0
  social:
    - icon: fontawesome/brands/github
      link: https://robertoborges.github.io/azure-containers-dotnet-workshop/
  analytics:
    provider: google
    property: G-Y20Y9XBPN4

extra_css:
  - assets/stylesheets/extra.css

repo_url: https://robertoborges.github.io/azure-containers-dotnet-workshop/
edit_uri: edit/main/docs